Feed page
dscnitrourkela/project-elaichi pull request #153
Opened 2021-12-17 15:26 UTC by nayakastha

# Your checklist for this pull request

🚨Please review the [guidelines for contributing](../CONTRIBUTING.md) to this repository.

- [ ] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). Don't request your default branch!
- [ ] Make sure you are making a pull request against the **default branch** (left side). Also you should start *your branch* off *default branch*.
- [ ] Check the commit's or even all commits' message styles matches our requested structure.
- [ ] Check your code additions will fail neither code linting checks nor unit test.
- [ ] I have added necessary documentation (if appropriate)

## Description
Feed Page UI Implemented

![app](https://user-images.githubusercontent.com/58568514/146567633-355f306e-eb07-4bec-971a-6cd1afe6acfd.jpeg)

💖Thank you!

## Post merge checklist

- [ ] Follow steps from the [guidelines for contributing](../CONTRIBUTING.md) to this repository.
- [ ] If you are a new contributor, ping in the thread and one of the maintainers will add you to all-contributors list.

2021-12-17 15:44 UTC, abhibhaw commented on elaichi/lib/feed/presentation/widgets/time_table_item.dart
> +import 'package:flutter/cupertino.dart';
Duplicate imports

2021-12-17 16:38 UTC, SriramPatibanda requested changes
Just move to string to strings folder.

2021-12-17 16:38 UTC, SriramPatibanda commented on elaichi/lib/feed/presentation/widgets/article_item.dart
> +                    Image.asset('assets/images/nitr.png', fit: BoxFit.cover),
Keep this in strings file.

2021-12-17 16:38 UTC, SriramPatibanda commented on elaichi/lib/feed/presentation/widgets/article_list.dart
> +                  'assets/images/mm.png',
Move to Strings file

2021-12-17 16:38 UTC, SriramPatibanda commented on elaichi/lib/feed/presentation/widgets/article_list.dart
> +                      'https://mondaymorning.nitrkl.ac.in/uploads/post/AIChE%20(4).png',
Strings folder

2021-12-17 16:38 UTC, SriramPatibanda commented on elaichi/lib/feed/presentation/widgets/time_table_item.dart
> +                    Image.asset('assets/images/add_event_icon.png'),
Strings folder

2021-12-17 16:38 UTC, SriramPatibanda commented on elaichi/lib/feed/presentation/widgets/zimbra_card.dart
> +                'assets/images/shader.png',
Strings folder

2021-12-17 17:08 UTC, nayakastha commented
![ave](https://user-images.githubusercontent.com/58568514/146581715-2c9c79da-d6af-41b3-8c80-6ad1427f18f1.jpeg)

2021-12-18 07:46 UTC, abhibhaw commented on elaichi/lib/feed/presentation/widgets/zimbra_card.dart
> +              'assets/images/nitr.png',
Ye rahh gya

2021-12-18 17:34 UTC, abhibhaw approved these changes

2021-12-19 07:06 UTC, SriramPatibanda approved these changes

2021-12-19 07:06 UTC, SriramPatibanda commented on elaichi/lib/app/utils/strings.dart
> +  static const String kCalendarLogoUri = 'assets/images/add_event_icon.png';
I understood that k isn't required as a prefix when were maintaining a separate class. We put k as a prefix as it's easier to search for constants with autocomplete when you just add 'k' in front of variables for global variables. But since Strings is a separate cases, just calling 'Strings.' will give us all the strings in our scope. I'll fix this in the next PR.

2021-12-19 07:08 UTC, nayakastha commented on elaichi/analysis_options.yaml
> +    lines_longer_than_80_chars: false
I wanted to disable it for the strings file only. I will change this in the next PR

2021-12-19 07:09 UTC, nayakastha commented on elaichi/lib/app/utils/strings.dart
> +  static const String kCalendarLogoUri = 'assets/images/add_event_icon.png';
Yes, also the names are pretty disoriented, we have to think of a common procedure to name them.

2021-12-19 07:10 UTC, nayakastha commented on elaichi/lib/app/utils/strings.dart
> +  static const String kCalendarLogoUri = 'assets/images/add_event_icon.png';
I am resolving this will fix it in today's PR

2021-12-19 07:10 UTC, merged