Calender UI v1
dscnitrourkela/project-elaichi pull request #177
Opened 2022-08-24 19:20 UTC by SriramPatibanda

# Your checklist for this pull request

🚨Please review the [guidelines for contributing](../CONTRIBUTING.md) to this repository.

- [x] Make sure you are requesting to **pull a topic/feature/bugfix branch** (right side). Don't request your default branch!
- [x] Make sure you are making a pull request against the **default branch** (left side). Also you should start *your branch* off *default branch*.
- [x] Check the commit's or even all commits' message styles matches our requested structure.
- [x] Check your code additions will fail neither code linting checks nor unit test.
- [x] I have added necessary documentation (if appropriate)

## Description

 - Add GraphQL Service
 - Add Event Model 
 - Add Event Repository
 - Fetch Events (Mock Data)
 - Upgrade Dependencies

💖Thank you!

## Post merge checklist

- [ ] Follow steps from the [guidelines for contributing](../CONTRIBUTING.md) to this repository.
- [ ] If you are a new contributor, ping in the thread and one of the maintainers will add you to all-contributors list.

2022-08-25 11:28 UTC, abhibhaw requested changes

2022-08-25 11:28 UTC, abhibhaw commented on elaichi/lib/data/remote/graphql/graphql_service.dart
> +      'https://test.dscnitrourkela.org/graphql',
R we planning to move it to remote config?

2022-08-25 11:28 UTC, abhibhaw commented on elaichi/lib/domain/models/event.freezed.dart
> +
Shouldn't we keep this in gitignore?

2022-08-25 11:28 UTC, abhibhaw commented on elaichi/lib/domain/models/event.g.dart
> +
same!!

2022-08-25 11:28 UTC, abhibhaw commented on elaichi/lib/presentation/profile/bloc/profile_bloc.dart
> +    await _eventRepository.fetchEvents();
You're rethrowing the error in fetchEvents, shouldn't it should be catched again here?

2022-08-25 11:28 UTC, abhibhaw commented on elaichi/lib/presentation/profile/bloc/profile_bloc.dart
> +    return _eventRepository.events;
Let's assume that the fetch event API call failed for some reason. Won't it throw late initialisation error here?

2022-08-25 11:28 UTC, abhibhaw commented on elaichi/lib/presentation/core/app.dart
> +    final graphQLService = GraphQLService()..init();
is this .. a type? or some syntax I'm not aware of?

2022-08-25 11:39 UTC, SriramPatibanda commented on elaichi/lib/domain/models/event.g.dart
> +
No need to do that for models and freezed packages. I want them in the repo.

2022-08-25 11:40 UTC, SriramPatibanda commented on elaichi/lib/presentation/profile/bloc/profile_bloc.dart
> +    await _eventRepository.fetchEvents();
Refresh and fetch events was a function I wrote for testing purposes. I'm not using it anywhere as of now.

2022-08-25 11:41 UTC, SriramPatibanda commented on elaichi/lib/presentation/core/app.dart
> +    final graphQLService = GraphQLService()..init();
It's a syntax that you don't know.

2022-08-25 11:42 UTC, SriramPatibanda commented on elaichi/lib/data/remote/graphql/graphql_service.dart
> +      'https://test.dscnitrourkela.org/graphql',
Let it be here as of now. I'm yet to decide how I would like to manage such links as I'll be using mm ke graphql also

2022-08-25 12:58 UTC, abhibhaw commented on elaichi/lib/presentation/core/app.dart
> +    final graphQLService = GraphQLService()..init();
Pls help me know a bit more abt this, any docs will be helpful :)

2022-08-25 13:01 UTC, riteshsp2000 commented on elaichi/lib/data/remote/graphql/graphql_service.dart
> +      'https://test.dscnitrourkela.org/graphql',
Let's try to manage things appropriately from the start. Refactoring it later will be a huge task. Ideally we shouldn't be going ahead with this.

2022-08-25 13:04 UTC, riteshsp2000 commented on elaichi/lib/presentation/profile/bloc/profile_bloc.dart
> +    await _eventRepository.fetchEvents();
If you are not using this then please remove it. If you plan to use it in future then add some sort of comment/indication that it isn't in use at the moment, here for furture purposes.

2022-08-25 13:05 UTC, SriramPatibanda commented on elaichi/lib/data/remote/graphql/graphql_service.dart
> +      'https://test.dscnitrourkela.org/graphql',
Yep, I'll make changes accordingly in the next PR with remote config service and MM integration

2022-08-25 13:06 UTC, SriramPatibanda commented on elaichi/lib/data/remote/graphql/graphql_service.dart
> +      'https://test.dscnitrourkela.org/graphql',
and no, refactoring this specific thing isn't going to be a huge task. It's pretty much decoupled from any service.

2022-08-25 13:06 UTC, riteshsp2000 commented on elaichi/lib/domain/models/event.g.dart
> +
Not sure what the appropriate way is, can someone please elaborate a bit here?

2022-08-25 13:10 UTC, SriramPatibanda commented on elaichi/lib/presentation/profile/bloc/profile_bloc.dart
> +    await _eventRepository.fetchEvents();
I tend to reuse it whenever I want and there's no collaborator as of now. I would want it to be here, I don't see any problem.

2022-08-25 13:14 UTC, SriramPatibanda commented on elaichi/lib/domain/models/event.g.dart
> +
https://www.reddit.com/r/FlutterDev/comments/kazxo0/do_you_add_gdart_files_to_gitignore/

it's mostly a preference.

2022-08-26 08:34 UTC, abhibhaw approved these changes

2022-08-26 08:34 UTC, merged